# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('idPersonne', models.IntegerField(primary_key=True, serialize=False)),
                ('nomAdministrateur', models.CharField(max_length=50)),
                ('prenomAdministrateur', models.CharField(max_length=50)),
                ('mailAdministrateur', models.CharField(max_length=50)),
                ('loginAdministrateur', models.CharField(max_length=50)),
                ('motDePasseAdministrateur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('refArticle', models.AutoField(primary_key=True, serialize=False)),
                ('nomArticle', models.CharField(max_length=50)),
                ('contenuArticle', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('idEvenement', models.AutoField(primary_key=True, serialize=False)),
                ('jourEvenement', models.DateField()),
                ('moisEvenement', models.DateField()),
                ('anneeEvenement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('refDocument', models.AutoField(primary_key=True, serialize=False)),
                ('nomDocument', models.CharField(max_length=50)),
                ('tailleDocument', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Administrateur')),
                ('refArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEvenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Calendrier')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idPersonne', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('refPlanning', models.AutoField(primary_key=True, serialize=False)),
                ('stockagePlanning', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Telecharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Personne')),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Administrateur')),
                ('refDocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Document')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('typeDocument', models.AutoField(primary_key=True, serialize=False)),
                ('libelleDocument', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('idTypeEvenement', models.AutoField(primary_key=True, serialize=False)),
                ('libelleEvenement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idPersonne', models.IntegerField(primary_key=True, serialize=False)),
                ('nomUtilisateur', models.CharField(max_length=50)),
                ('prenomUtilisateur', models.CharField(max_length=50)),
                ('mailUtilisateur', models.CharField(max_length=50)),
                ('loginUtilisateur', models.CharField(max_length=50)),
                ('motDePasseUtilisateur', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='modifier',
            name='refEvenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Planning'),
        ),
        migrations.AddField(
            model_name='document',
            name='typeDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.TypeDocument'),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='idTypeEvenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.TypeEvenement'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='refPlanning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Planning'),
        ),
    ]
