# Generated by Django 2.2.7 on 2019-12-13 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dateArticle',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datede parution'),
            preserve_default=False,
        ),
    ]
