# Generated by Django 2.2.7 on 2019-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0002_article_datearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenuArticle',
            field=models.TextField(max_length=500),
        ),
    ]
