# Generated by Django 2.2.7 on 2019-12-14 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0003_auto_20191213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photoArticle',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
