# Generated by Django 2.2.7 on 2019-12-15 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0004_article_photoarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('refPhoto', models.AutoField(primary_key=True, serialize=False)),
                ('stockagePhoto', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Ajouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Administrateur')),
                ('refPhoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmkaPage.Photo')),
            ],
        ),
    ]
