# Generated by Django 2.2.7 on 2019-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0006_auto_20191215_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photoArticle',
            field=models.ImageField(blank=True, upload_to='photos_ecole'),
        ),
    ]
