# Generated by Django 2.2.7 on 2019-12-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0007_auto_20191216_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='stockagePhoto',
        ),
    ]
