# Generated by Django 2.2.7 on 2019-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0008_remove_photo_stockagephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photoArticle',
        ),
        migrations.AddField(
            model_name='photo',
            name='stockagePhoto',
            field=models.ImageField(blank=True, upload_to='photos_ecole'),
        ),
    ]
