# Generated by Django 2.2.7 on 2019-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0009_auto_20191216_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photoArticle',
            field=models.ImageField(blank=True, upload_to='photos_ecole'),
        ),
    ]
