# Generated by Django 2.2.7 on 2019-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmkaPage', '0010_article_photoarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajouter',
            name='ajouterPhoto',
            field=models.ImageField(blank=True, upload_to='photos_ecole'),
        ),
    ]
